version: '3'
services:

  dtl-influxdb:
    image: influxdb:1.7.8
    container_name: dtl-influxdb
    environment:
      - INFLUXDB_CONFIG_PATH=/etc/influxdb/influxdb.conf
    ports:
      - 8086:8086
      - 8089:8089/udp
    volumes:
      - ./data/influxdb:/var/lib/influxdb
      - ./etc/influxdb.conf:/etc/influxdb/influxdb.conf:ro

  dtl-mysql:
    image: mysql:latest
    container_name: dtl-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=puyuantech
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql/logs:/logs
      - ./data/mysql/conf:/etc/mysql/conf.d
      - ./data/mysql/data:/var/lib

  dtl-grafana:
    image: grafana/grafana:latest
    container_name: dtl-grafana
    user: "0"
    ports:
      - 3000:3000
    links:
      - dtl-influxdb
    volumes:
      - ./data/grafana:/var/lib/grafana

  dtl-main:
    image: puyuantech/cryptofx:latest
    container_name: dtl-main
    environment:
      - TLCLIENT_LOG_LEVEL=info
    ports:
      - 9000-9007:9000-9007
    links:
      - dtl-influxdb
    command: >
        bash -c "sleep 3 &&
                gun start master &&
                gun start mr -f market1 &&
                gun start mg -g binance -p cryptofx
                gun start mg -g bitmex -p cryptofx
                gun start mg -g huobi -p cryptofx
                gun start mg -g okex -p cryptofx
                gun start rr --rt influxdb --host dtl-influxdb --port 8086
                gun join master"
    volumes:
      - ./data/main:/shared
